SET C251INC=D:\tools\Keil_v5\C251\Inc;D:\tools\Keil_v5\C251\Inc\STC
SET C251LIB=D:\tools\Keil_v5\C251\Lib
SET CPU_TYPE=STC16F40K128 Series
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02160EC0
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\main.__i
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_ADC.__i
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_GPI~1.__I
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_GPI~2.__I
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_GPI~3.__I
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_I2C.__i
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_OLE~1.__I
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_PWM.__i
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_SPI.__i
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_TIMER.__i
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_ICM~1.__I
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_SOF~1.__I
"D:\tools\Keil_v5\C251\BIN\C251.EXE" @.\Objects\LQ_MPU~1.__I
"D:\tools\Keil_v5\C251\BIN\LIB251.EXE" @".\Objects\LQdemo.__b"
